### ISSUE TITLE
RTE link options

### ISSUE THREAD

**Issue by lele7** [imulus/Archetype#182]
I use the rte editor in archetype. when I want to add a link with options for instance in a new window the options aren't saved... do you have any idea how I can fix this?

**Comment by tomfulton** [comment]
Just an update - this is still an issue in the latest versions.  It does not happen with the normal RTE, only when within an Archetype.  I found out the Grid has the same exact issue, so I logged [U4-6395](http://issues.umbraco.org/issue/U4-6395) as well.

Doing some debugging, this works on a normal page because when you click Save/Publish, it triggers [this event](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js#L276-L281) in the RTE's controller.  This event still gets fired when in an Archetype, but Archetype never gets the updated value (maybe something with ordering of operations?).

Hopefully the Umbraco guys will have some insight in relation to the grid that will help us.

**Comment by kgiszewski** [comment]
:+1:

**Comment by kgiszewski** [comment]
I found the bug in the core and I'm submitting a PR.  Will keep status updated here.

**Comment by kgiszewski** [comment]
https://github.com/umbraco/Umbraco-CMS/pull/653

**Comment by tomfulton** [comment]
@kgiszewski fix looks to correct the issue for me in both Archetype and the Grid!  #h5yr :heart: :100:

Will keep this open until it gets merged, but adding that line manually should get you by for now.

**Comment by kgiszewski** [comment]
Fixed in core.
