### ISSUE TITLE
Can No Longer Use Multiple Fields in Label Templates

### ISSUE THREAD

**Issue by Nicholas-Westby** [imulus/Archetype#276]
Take a look at this fieldset:
![fieldset](https://cloud.githubusercontent.com/assets/5933222/8014808/9e3242e0-0b88-11e5-9167-6bd76bfc0f23.png)

Notice I'm trying to render two fields in the label template. I could swear this used to work, but it doesn't any longer. I can render either one of those fields, but I can't use them both at once (shows up as an empty label).

Umbraco 7.2.6. Archetype 1.8.

**Comment by kgiszewski** [comment]
Hmmm, well strangely I can't ever confirm it ever worked for more than one so I'll take your word for it.  I'll have to look at it next week.  You going to Codegarden?

**Comment by martijn1k** [comment]
Thanks for reporting this. I thought I encountered a bug (not seeing labels at all) due to the upgrade to 7.2.6.

I can confirm the labels are now missing when you add more than one since the 7.2.6 update. We're running another instance on 7.2.1 and multiple fields work fine there. If I remove the additional field (a date field) then it works. I also tried showing just the date field, also works fine.

So I guess showing just the name is the work-arround for now.

**Comment by kgiszewski** [comment]
Apologies for the broken feature. I may look at it this week at Codegarden.

**Comment by martijn1k** [comment]
Dude. Spare us the apologies! A small bug in probably the best Umbraco package there is.
Thanks for creating this, it's seriously awesome.

Have fun at Codegarden.

**Comment by kgiszewski** [comment]
Wow thanks! :)

**Comment by Nicholas-Westby** [comment]
Nope, not going to Codegarden. Thanks for confirming, @martijn1k .

**Comment by kgiszewski** [comment]
Looks like I've got this fixed. Should be in the next patch released scheduled for July.  You can try it out now if you need it sooner.
