### ISSUE TITLE
Courier for Archetype as a Nuget Package

### ISSUE THREAD

**Issue by kgiszewski** [imulus/Archetype#314]
@leekelleher Do you see much value in having a Nuget package for your Courier DLL?

Right now it's only offered as a downloadable file.

**Comment by leekelleher** [comment]
I'm cool with a NuGet package for it.  Only reason I hadn't looked at it before is that I wasn't sure of the demand for it, but makes sense.

Is it something that is easily added to the existing build process? or would you need me to do something for it?

**Comment by kgiszewski** [comment]
I can handle it, but I also needed to know if it was worth the effort.

I just added a binary only Nuget package today to the build process. Should be just a matter of updating my grunt file. https://github.com/imulus/Archetype/commit/16351df6924a951e0be70b236dd5ef8a108ec943

But before I do it, I wanted to see if you knew how many people might be using it. If you aren't sure, then that's ok too.

**Comment by leekelleher** [comment]
I'm not sure on exact numbers... I know of at least 5 people using it (and that's only because they've told me at meetups/UK-festival) :smiley: 

I expect more demand as UaaS opens more invitations up.

As for NuGet dependencies, it does reference "UmbracoCms.Core" package, (as well as new "Archetype.Binaries", _obviously_ :wink:), but also the Courier DLLs - but those aren't publicly available on NuGet.  I guess we're safe to leave them out, as anyone installing this should already be aware of Courier.

**Comment by kgiszewski** [comment]
:+1: FYI, I'm targeting Umb Core 7.2.2+ in case it matters. If I get a chance this week I'll create a Nuget package for this to make it easier for some.

**Comment by leekelleher** [comment]
Umb 7.2.2 is cool with me :+1:  Give me a shout when you need me to test it out.

**Comment by kgiszewski** [comment]
@leekelleher  Ready for testing: https://www.nuget.org/packages/Archetype.Courier

It may take a few minutes to update the index in your neighborhood.

**Comment by leekelleher** [comment]
Rock-n-roll! :metal::metal::metal:

**Comment by kgiszewski** [comment]
Ok to tweet this out?

**Comment by leekelleher** [comment]
Yup, good to tweet.

**Comment by kgiszewski** [comment]
Awesome, thanks again for your work on everything #h5yr!
