### ISSUE TITLE
Group Unset When Applying Global Fieldset Options

### ISSUE THREAD

**Issue by Nicholas-Westby** [imulus/Archetype#323]
See demo:

![group](https://cloud.githubusercontent.com/assets/5933222/12491533/7d0efcd6-c030-11e5-8fda-2b105ec060fb.gif)

If my fieldsets have a group assigned and I click `Global Fieldset Options` then `Apply`, the dropdown containing the group is unset. I'm now hesitant to add any new groups or change any global settings, as I'm afraid that will unset all the groups I've set on my many fieldsets.

**Comment by kgiszewski** [comment]
Ok, thanks for the report. I'll try to replicate soon and possibly ping @kjac on this one.

**Comment by kjac** [comment]
Whoa. I'll see if I can repro and fix in the weekend.

**Comment by Nicholas-Westby** [comment]
FYI, I think this was Umbraco 7.3.4 and Archetype 1.12.2

**Comment by kjac** [comment]
Okay I can reproduce on 7.3.5 and 1.12.2.

@kgiszewski it happens because the entire configuration model gets cloned when spawning the configuration dialogs. This breaks the object references between the fieldsets and the groups. I can code my way around it, but this will most likely keep happening over time as the configuration model grows in complexity.

It is worth considering an alternative approach that does not involve copying the configuration model. For example if the actual configuration model was "live edited" in the dialogs, this would not be a problem. The drawback is that we'd need to remove the "cancel" button and change "apply" to "ok" since there'd be no cancelling the changes.

Your thoughts?

**Comment by kgiszewski** [comment]
@kjac I think a live edit would be ideal. I think I attempted it when I moved things to dialogs but ran into trouble that I can't quite recall at the moment. If you think we can 'live' edit it, I think that's a good option.

**Comment by kjac** [comment]
I'll give it a go, probably tomorrow :-)

**Comment by kjac** [comment]
@kgiszewski I had a bit of time to work on this issue... PR #324 should fix it. 

I can't make it break, but maybe you can remember what you did to break it when you added the dialogs :)

**Comment by kgiszewski** [comment]
Yep, I'll test all of the dialog features to make sure we're not regressing on anything. Thanks again.
