### ISSUE TITLE
Feature request: publish/unpublish date

### ISSUE THREAD

**Issue by seanhak** [imulus/Archetype#334]
Archetype is great, it has replaced the tedious work of creating new "pages" every time you wanted a data entry added.
However one of the percs with the "old" system was that the editor could easily set a start and stop publish date for temp campaigns.

Right now it's pretty easy to implement your own date fields and check those, however it would be nice if there was a UI hint, or even better if it was automatically enabled/disabled.

I guess a UI hint should be fairly easy if I write my own view that checks if current date is within a date span.

**Comment by kjac** [comment]
@seanhak What a fantastic idea. I love it. 

@kgiszewski whatcha think? I'm up for implementing it - tho' a UI prototype should probably be the first thing on the list.

**Comment by kgiszewski** [comment]
Sounds like a plan. I'm curious how the UI/implementation would look so let's start there.

**Comment by kjac** [comment]
Here's a suggestion. On second thought, the wording in the labels etc. should probably not be as much about "expiry" but more about "unpublishing". 

I considered hiding the setting somewhere fancy... but the way I see it, support for fieldset expiry will be explicitly enabled in the archetype config when it's applicable. In other words - if it's enabled, it's supposed to be used actively by the content editors, so the best choice is probably to make it very visible.

![archetype-expiry](https://cloud.githubusercontent.com/assets/7405322/13473258/e363f5f6-e0b8-11e5-9047-dc268243f8e8.png)

**Comment by seanhak** [comment]
Nice work @kjac !
I think start date is also pretty important. Let's say the client has a new product on a sunday, and wants to schedule a carousel item for sunday night.

I would also prefer to differentiate from other properties. maybe a fieldset or panel.

I don't have a big insight in to the inner workings, so alot of my suggestions might be unrealistic or very big hit on performance.

If we have a clock icon that toggles start/stop publish "mode"(fields), that could be used to to notify user that this item is pending, or unpublished, without opening each fieldset and check.
Or, if a fieldset has been unpublished(disabled) just return it to idle/normal state, ie.
set is disabled, and dates cleared. clock icon "normal state".

**Comment by kjac** [comment]
Let's see then... how about this? 

1. Publish and unpublish dates at the bottom under the punctuated line which separates them from the rest of the fieldset properties. 
2. Add a clock icon to the title bar when the fieldset is pending either publish or unpublish (current date/time is before publish or unpublish).
3. The fieldset is automatically disabled when the unpublish date is exceeded.
4. No matter the publish settings, the users can always explicitly disable the fieldset.

![archetype-publish](https://cloud.githubusercontent.com/assets/7405322/13546634/d71496e6-e2b3-11e5-9dd6-8a43a4935c5c.png)

**Comment by kgiszewski** [comment]
Looks good. I think this should be something that is turned off/on in the configuration per entire Archetype maybe. By default it is disabled. 

Curious on the mechanism to publish/unpublish. Simply return on published fieldsets

**Comment by kgiszewski** [comment]
I was originally editing this on my phone and accidentally closed it with half of a comment :(

**Comment by kjac** [comment]
@kgiszewski shouldn't you be enjoying yourself at uWest instead of slaving over PRs? :smile: 

I agree on your thoughts. Specially that this feature should explicitly be turned on per Archetype configuration.

With regards to handling un/publishing, I think it'll be as simple as weeding out the fieldsets that should not be published at the time of rendering - exactly like we do with the disabled fieldsets. I'm gonna mull it over a bit, but maybe it would actually make sense to hook this feature into the disabled fieldsets feature, thus letting a fieldset appear as disabled from a code perspective if it's not yet published.

I'm gonna try to find some time tomorrow to prototype a little.

**Comment by kgiszewski** [comment]
@kjac, conference is over, can't sleep but putting out other fires :) I'll let you do your thing here.

**Comment by kjac** [comment]
@kgiszewski OK... the prototype works quite well (backoffice only), but I've realized a few things making it.

First thing: Since the publishing implicitly affects the enabled state of a fieldset, we need to be able to distinguish between explicitly disabled fieldsets and fieldsets that have been disabled by their publish settings. I suggest letting the power-icon light up when the fieldset is explicitly disabled. This would also benefit Archetype configs without publishing. See screenshot below.

Second thing: The users need to be able to see which fieldsets have been or will be affected by their publish settings (i.e. not yet released, about to expire or already expired) - preferably at a glance. The best solution I've come up with is letting the clock icon be visible for all fieldsets regardless of their publish state, and make it light up when the fieldsets are affected by their publish settings. The screenshot below shows the different cases:

![archetype-publish-2](https://cloud.githubusercontent.com/assets/7405322/13555133/7f9241ec-e3b8-11e5-890a-2bd7484d30ba.png)

* Case 1: The fieldset will expire in the future - the clock icon lights up
* Case 2: The fieldset is explicitly disabled - the power icon lights up and the title is dimmed
* Case 3: The fieldset is expired - the clock icon lights up and and the title is dimmed
* Case 4: The fieldset has no publish settings configured - the clock icon is dimmed
* Case 5: The fieldset is not yet released - the clock icon lights up and and the title is dimmed
* Case 6: The fieldset is released and has no expiry - the clock icon is dimmed

Thoughts?

**Comment by kgiszewski** [comment]
First off, great work! Your screenshot is super helpful and may need to go into the docs. My only concern is the large number of combinations that might make editors get confused. 

I'm not suggesting I have a way to make things clearer, but allow me to spitball a bit.

Perhaps the clock icon could have subtle clues that indicate things such as having a release date or expiry date.

Where I'm going with this is if I have only 1 or 2 fieldsets configured, will I know at a glance what is configured without looking at the fieldset opened?

Maybe I will after using it for a bit.

I'm in Las Vegas for a few more days so I'll try to be more helpful next week.

**Comment by kjac** [comment]
Vegas, baby!

Have fun. There's no rush with this. We'll pick it up when you're back home
again.

**Comment by seanhak** [comment]
@kjac Great work!

So here is my thoughts.
What if the clock icon replaces the normal enable/disable button?
It would implicate that the clock and on/off is the same, just with a timer. 
And maybe more clear for user. 
Also it would prevent weird cases such as the user enables a set that isn't 
supposed to be enabled due to time.(?)
(Icon suggestions: http://uxrepo.com/static/icon-sets/google-material/svg/android-timer.svg, http://www.moulinex.ca/wp-content/uploads/2013/10/icon-power-timer.png)

I still believe a different UI for the date fields would make it clearer to the user that 
these are: 1, optional. 2, these are not data entry, these are functional entries.

An inline toggle to show these fields may also emphasize that this is an option to enable a feature.
This is especially true if a field set already contains 1 or more "normal" date pickers. But might make it too complicated/confusing with too many "do's" for user.

Thanks again for taking your time looking in to this, this feature will be used a lot by us (and many others I think), 
We are already using a poor mans version of this, with date fields and handling in template.

**Comment by kjac** [comment]
@seanhak good input. 

We can't replace the power icon, that'd leave the editors without an option to explicitly disable the fieldset (since the power icon is the only way of doing so).

As for icons we're pretty much stuck with the icons offered by Umbraco - those available when creating new content types. There are a few clock/time icons there, I just picked the one that I liked the best :)

Personally I'm not a big fan of hiding things from the editors behind a toggle. But that's just me. The publish/unpublish date pickers could easily be put behind a "Fieldset settings" toggle in the bottom of the fieldset. Design suggestions are welcome.

**Comment by kgiszewski** [comment]
Can we replace the power icon dynamically when a timer is set?

So if a date/time exists, either expiry or release, the power icon changes to a clock.

When it expires, the clock becomes the normal power button.

Still just spitballing.

**Comment by kjac** [comment]
Sure we can, but as I pointed out earlier, this will deprive the editors of
the possibility to disable the fieldsets explicitly when a timer is in
effect.

I'll post an updated screenshot of the prototype soon, I think the solution
may be as simple as to not show the clock icon as active when the timer is
in effect. I'll get back to you soon :-)

**Comment by kgiszewski** [comment]
Ok no worries. I'm pushing a release today so we have plenty of time to debate.

**Comment by kjac** [comment]
Aaaaaalright y'all might just have a point :)

![archetype-publish-3](https://cloud.githubusercontent.com/assets/7405322/13679222/05efe9dc-e6f3-11e5-9527-2daaabdac881.png)

Replacing the power icon with the clock icon makes sense, because now they have the same meaning - namely "this fieldset is disabled because of me".

For this to work, the archetype config might be required to have enabled both "publishing" and "disabling".

**Comment by kjac** [comment]
I've added an expandable "Settings" section per fieldset with a gray background to make it easier to distinguish the fieldset settings from the fieldset content.

![archetype-publish-4](https://cloud.githubusercontent.com/assets/7405322/13904601/8945d2a0-eea6-11e5-8bcf-92cd68e28acd.png)

Also notice that if a fieldset is both disabled and unpublished, only the power icon will be visible as the disabled state takes precedence.

![archetype-publish-5](https://cloud.githubusercontent.com/assets/7405322/13904602/9f48b9b4-eea6-11e5-9b37-1a37a73ea62f.png)

Comments? Thoughts?

**Comment by kgiszewski** [comment]
@kjac Looking real good.

Question (possibly already addressed earlier): Can we toggle on the the publishing bit? Meaning, you only get the publishing bits if you opt-in in the config.

You may have already answered this so apologies ahead of time.

**Comment by kjac** [comment]
No reason to apologize. Yes publishing (and all derived effects thereof) is
optional by configuration, default disabled.

I'll post a PR soon :-)

**Comment by kgiszewski** [comment]
Reviewing #340 soon regarding this.
